package:
  name: gaminet
  version: "0.1"

source:
   - path: ../

build:
   noarch: python
   number: 1
   script:
    - export PYTHONUNBUFFERED=1  # [ppc64le]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . --global-option="build_ext" # [not unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . --global-option="build_ext" --global-option="-j${CPU_COUNT}" --no-use-pep517  # [unix] 


requirements:
  build:
    - python {{PY_VER}}
    - pip
    - numpy                               
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python {{PY_VER}}
    - pip
    - numpy

  run:
    - python {{PY_VER}}
    - numpy>=1.15.2
    - matplotlib>=3.1.3
    - numpy>=1.18 
    - tensorflow>=2.0.0
    - pandas>=0.19.2
    - scikit-learn>=0.23.0

tests:
  imports:
    - gaminet 

about:
  home: https://github.com/ZebinYang/gaminet 
  license: proprietary 
  summary: Generalized additive model with pairwise interactions
