package:
  name: gaminet
  version: "0.1"

source:
   - path: ../

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"


requirements:
  host:
    - pip
    - python

  run:
    - python>=3.7
    - numpy>=1.15.2
    - matplotlib>=3.1.3
    - tensorflow>=2.0.0
    - pandas>=0.19.2
    - scikit-learn>=0.23.0

tests:
  imports:
    - gaminet 

about:
  home: https://github.com/ZebinYang/gaminet 
  license: GPL
  summary: Generalized additive model with pairwise interactions
